version: '3.8'

services:
  api:
    build: ./
    container_name: assistant-api
    command: python manage.py run
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    env_file:
      - ./.env-prod
#     depends_on:
#       - db
#   db:
#     image: postgres:13
#     container_name: assistant-db
#     volumes:
#       - ~/pg_data:/var/lib/postgresql/data
#     env_file:
#       - ./.env.prod.db  
#     ports:
#       - "5433:5433"  
    
# volumes:
#   postgres_data:
